# Generated by Django 5.0.7 on 2024-09-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=30)),
                ('task_priority', models.CharField(max_length=10)),
                ('task_duedate', models.DateField()),
            ],
        ),
    ]
