# Generated by Django 5.0.7 on 2024-09-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_duedate',
            field=models.CharField(max_length=10),
        ),
    ]
